
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador.sintactic;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int ST = 37;
  public static final int CONST = 38;
  public static final int LBRA = 13;
  public static final int RESTA = 27;
  public static final int INT = 2;
  public static final int RCOR = 12;
  public static final int AND = 19;
  public static final int IGUAL = 17;
  public static final int RPAR = 10;
  public static final int OR = 18;
  public static final int DIV = 33;
  public static final int MAJOR = 21;
  public static final int NUM = 31;
  public static final int SUMA = 26;
  public static final int IF = 4;
  public static final int ID = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 8;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int COMA = 15;
  public static final int RBRA = 14;
  public static final int MENOR = 20;
  public static final int ET = 36;
  public static final int VOID = 34;
  public static final int PCOMA = 16;
  public static final int ELSE = 5;
  public static final int IGUALIGUAL = 23;
  public static final int WHILE = 6;
  public static final int LCOR = 11;
  public static final int MENORIG = 25;
  public static final int MAJORIG = 24;
  public static final int PROD = 32;
  public static final int LPAR = 9;
  public static final int UWU = 35;
  public static final int FALSE = 29;
  public static final int DO = 7;
  public static final int NOTEQ = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "RETURN",
  "LPAR",
  "RPAR",
  "LCOR",
  "RCOR",
  "LBRA",
  "RBRA",
  "COMA",
  "PCOMA",
  "IGUAL",
  "OR",
  "AND",
  "MENOR",
  "MAJOR",
  "NOTEQ",
  "IGUALIGUAL",
  "MAJORIG",
  "MENORIG",
  "SUMA",
  "RESTA",
  "TRUE",
  "FALSE",
  "ID",
  "NUM",
  "PROD",
  "DIV",
  "VOID",
  "UWU",
  "ET",
  "ST",
  "CONST"
  };
}

